---
# EC2NodeClass — dev.
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: echo-pong-dev
spec:
  role: echo-pong-dev-karpenter-node
  amiSelectorTerms:
    - alias: al2023@latest
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: echo-pong-dev
        kubernetes.io/role/internal-elb: "1"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: echo-pong-dev
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 1
    httpTokens: required
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 20Gi
        volumeType: gp3
        encrypted: true
        deleteOnTermination: true
  detailedMonitoring: false
  tags:
    Environment: dev
    Application: echo-pong
    ManagedBy: karpenter
    Repository: echo-pong-gitops
